spring.application.name=backend
server.port=8081
# Activate the 'dev' profile locally
spring.profiles.active=dev

# Database Connection (Safe to share the URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/CampusHireDB
spring.datasource.username=postgres
spring.datasource.password=Ragul

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.example.backend=INFO
logging.level.com.example.backend.AOPs=INFO
logging.level.org.springdoc=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN


# JWT
jwt.secret=change_me_to_a_256bit_secret_key_value_change_me_please
jwt.expiration-ms=86400000
